[build]
  command = "npm run build"
  publish = ".next"

# Use the official Next.js plugin for Netlify to handle SSR/ISR and routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: environment variables can also be set here for local builds (prefer Netlify UI for production)
# [build.environment]
#   THESYS_API_KEY = "your-thesys-api-key"